apiVersion: v1
kind: Service
metadata:
  name: weatherclient
  namespace: development
spec:
  selector:
    app: weatherclient
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: 8888
  type: ClusterIP

