apiVersion: v1
kind: Service
metadata:
  name: weatherui
  namespace: development
spec:
  selector:
    app: weatherui
  ports:
    - name: http
      protocol: TCP
      port: 1234
      targetPort: 1234
  type: ClusterIP

