spring :
  application :
    name : weathermapclient

eureka:
  client:
    serviceUrl:
      defaultZone: http://serviceregistry:8761/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
 
    
server :
  port : 8888
  shutdown : graceful
  
management :
  health :
    livenessstate :
      enabled : true
    readinessstate :
      enabled : true
  info :
    env :
      enabled : true
  server :
    add-application-context-header : true
  endpoints :
    enabled-by-default : false
    web :
      exposure :
        include : health, prometheus, info, openapi, swagger-ui
  endpoint :
    health :
      enabled : true
      show-details : always
      probes :
        enabled : true
    prometheus :
      enabled : true
    info :
      enabled : true

springdoc :
  show-actuator : false
  swagger-ui :
    config-url : ${SWAGGER_UI_RELATIVE_PATH:/}v3/api-docs/swagger-config
    url : ${SWAGGER_UI_RELATIVE_PATH:/}v3/api-docs
