apiVersion: v1
kind: Service
metadata:
  name: serviceregistry
  namespace: development
spec:
  selector:
    app: serviceregistry
  ports:
    - name: http
      protocol: TCP
      port: 8761
      targetPort: 8761
  type: ClusterIP

